<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('country_prefixes', function (Blueprint $table) {
            $table->id();
            $table->string('prefix', 5)->unique();
            $table->string('country_code', 2);
            $table->string('country_name');
            $table->timestamps();
        });

        $prefixes = [
            ['prefix' => '1', 'country_code' => 'US', 'country_name' => 'USA'],
            ['prefix' => '7', 'country_code' => 'RU', 'country_name' => 'Russia'],
            ['prefix' => '20', 'country_code' => 'EG', 'country_name' => 'Egypt'],
            ['prefix' => '27', 'country_code' => 'ZA', 'country_name' => 'South Africa'],
            ['prefix' => '30', 'country_code' => 'GR', 'country_name' => 'Greece'],
            ['prefix' => '31', 'country_code' => 'NL', 'country_name' => 'Netherlands'],
            ['prefix' => '32', 'country_code' => 'BE', 'country_name' => 'Belgium'],
            ['prefix' => '33', 'country_code' => 'FR', 'country_name' => 'France'],
            ['prefix' => '34', 'country_code' => 'ES', 'country_name' => 'Spain'],
            ['prefix' => '36', 'country_code' => 'HU', 'country_name' => 'Hungary'],
            ['prefix' => '39', 'country_code' => 'IT', 'country_name' => 'Italy'],
            ['prefix' => '40', 'country_code' => 'RO', 'country_name' => 'Romania'],
            ['prefix' => '41', 'country_code' => 'CH', 'country_name' => 'Switzerland'],
            ['prefix' => '43', 'country_code' => 'AT', 'country_name' => 'Austria'],
            ['prefix' => '44', 'country_code' => 'GB', 'country_name' => 'United Kingdom'],
            ['prefix' => '45', 'country_code' => 'DK', 'country_name' => 'Denmark'],
            ['prefix' => '46', 'country_code' => 'SE', 'country_name' => 'Sweden'],
            ['prefix' => '47', 'country_code' => 'NO', 'country_name' => 'Norway'],
            ['prefix' => '48', 'country_code' => 'PL', 'country_name' => 'Poland'],
            ['prefix' => '49', 'country_code' => 'DE', 'country_name' => 'Germany'],
            ['prefix' => '51', 'country_code' => 'PE', 'country_name' => 'Peru'],
            ['prefix' => '52', 'country_code' => 'MX', 'country_name' => 'Mexico'],
            ['prefix' => '53', 'country_code' => 'CU', 'country_name' => 'Cuba'],
            ['prefix' => '54', 'country_code' => 'AR', 'country_name' => 'Argentina'],
            ['prefix' => '55', 'country_code' => 'BR', 'country_name' => 'Brazil'],
            ['prefix' => '56', 'country_code' => 'CL', 'country_name' => 'Chile'],
            ['prefix' => '57', 'country_code' => 'CO', 'country_name' => 'Colombia'],
            ['prefix' => '58', 'country_code' => 'VE', 'country_name' => 'Venezuela'],
            ['prefix' => '60', 'country_code' => 'MY', 'country_name' => 'Malaysia'],
            ['prefix' => '61', 'country_code' => 'AU', 'country_name' => 'Australia'],
            ['prefix' => '62', 'country_code' => 'ID', 'country_name' => 'Indonesia'],
            ['prefix' => '63', 'country_code' => 'PH', 'country_name' => 'Philippines'],
            ['prefix' => '64', 'country_code' => 'NZ', 'country_name' => 'New Zealand'],
            ['prefix' => '65', 'country_code' => 'SG', 'country_name' => 'Singapore'],
            ['prefix' => '66', 'country_code' => 'TH', 'country_name' => 'Thailand'],
            ['prefix' => '81', 'country_code' => 'JP', 'country_name' => 'Japan'],
            ['prefix' => '82', 'country_code' => 'KR', 'country_name' => 'South Korea'],
            ['prefix' => '84', 'country_code' => 'VN', 'country_name' => 'Vietnam'],
            ['prefix' => '86', 'country_code' => 'CN', 'country_name' => 'China'],
            ['prefix' => '90', 'country_code' => 'TR', 'country_name' => 'Turkey'],
            ['prefix' => '91', 'country_code' => 'IN', 'country_name' => 'India'],
            ['prefix' => '92', 'country_code' => 'PK', 'country_name' => 'Pakistan'],
            ['prefix' => '212', 'country_code' => 'MA', 'country_name' => 'Morocco'],
            ['prefix' => '216', 'country_code' => 'TN', 'country_name' => 'Tunisia'],
            ['prefix' => '250', 'country_code' => 'RW', 'country_name' => 'Rwanda'],
            ['prefix' => '251', 'country_code' => 'ET', 'country_name' => 'Ethiopia'],
            ['prefix' => '252', 'country_code' => 'SO', 'country_name' => 'Somalia'],
            ['prefix' => '254', 'country_code' => 'KE', 'country_name' => 'Kenya'],
            ['prefix' => '256', 'country_code' => 'UG', 'country_name' => 'Uganda'],
            ['prefix' => '260', 'country_code' => 'ZM', 'country_name' => 'Zambia'],
            ['prefix' => '263', 'country_code' => 'ZW', 'country_name' => 'Zimbabwe'],
            ['prefix' => '298', 'country_code' => 'FO', 'country_name' => 'Faroe Islands'],
            ['prefix' => '350', 'country_code' => 'GI', 'country_name' => 'Gibraltar'],
            ['prefix' => '351', 'country_code' => 'PT', 'country_name' => 'Portugal'],
            ['prefix' => '352', 'country_code' => 'LU', 'country_name' => 'Luxembourg'],
            ['prefix' => '353', 'country_code' => 'IE', 'country_name' => 'Ireland'],
            ['prefix' => '354', 'country_code' => 'IS', 'country_name' => 'Iceland'],
            ['prefix' => '355', 'country_code' => 'AL', 'country_name' => 'Albania'],
            ['prefix' => '356', 'country_code' => 'MT', 'country_name' => 'Malta'],
            ['prefix' => '357', 'country_code' => 'CY', 'country_name' => 'Cyprus'],
            ['prefix' => '358', 'country_code' => 'FI', 'country_name' => 'Finland'],
            ['prefix' => '359', 'country_code' => 'BG', 'country_name' => 'Bulgaria'],
            ['prefix' => '370', 'country_code' => 'LT', 'country_name' => 'Lithuania'],
            ['prefix' => '371', 'country_code' => 'LV', 'country_name' => 'Latvia'],
            ['prefix' => '372', 'country_code' => 'EE', 'country_name' => 'Estonia'],
            ['prefix' => '373', 'country_code' => 'MD', 'country_name' => 'Moldova'],
            ['prefix' => '374', 'country_code' => 'AM', 'country_name' => 'Armenia'],
            ['prefix' => '375', 'country_code' => 'BY', 'country_name' => 'Belarus'],
            ['prefix' => '376', 'country_code' => 'AD', 'country_name' => 'Andorra'],
            ['prefix' => '377', 'country_code' => 'MC', 'country_name' => 'Monaco'],
            ['prefix' => '378', 'country_code' => 'SM', 'country_name' => 'San Marino'],
            ['prefix' => '380', 'country_code' => 'UA', 'country_name' => 'Ukraine'],
            ['prefix' => '381', 'country_code' => 'RS', 'country_name' => 'Serbia'],
            ['prefix' => '382', 'country_code' => 'ME', 'country_name' => 'Montenegro'],
            ['prefix' => '383', 'country_code' => 'XK', 'country_name' => 'Kosovo'],
            ['prefix' => '385', 'country_code' => 'HR', 'country_name' => 'Croatia'],
            ['prefix' => '386', 'country_code' => 'SI', 'country_name' => 'Slovenia'],
            ['prefix' => '387', 'country_code' => 'BA', 'country_name' => 'Bosnia and Herzegovina'],
            ['prefix' => '389', 'country_code' => 'MK', 'country_name' => 'North Macedonia'],
            ['prefix' => '420', 'country_code' => 'CZ', 'country_name' => 'Czech Republic'],
            ['prefix' => '421', 'country_code' => 'SK', 'country_name' => 'Slovakia'],
            ['prefix' => '423', 'country_code' => 'LI', 'country_name' => 'Liechtenstein'],
            ['prefix' => '500', 'country_code' => 'FK', 'country_name' => 'Falkland Islands'],
            ['prefix' => '501', 'country_code' => 'BZ', 'country_name' => 'Belize'],
            ['prefix' => '502', 'country_code' => 'GT', 'country_name' => 'Guatemala'],
            ['prefix' => '503', 'country_code' => 'SV', 'country_name' => 'El Salvador'],
            ['prefix' => '504', 'country_code' => 'HN', 'country_name' => 'Honduras'],
            ['prefix' => '505', 'country_code' => 'NI', 'country_name' => 'Nicaragua'],
            ['prefix' => '506', 'country_code' => 'CR', 'country_name' => 'Costa Rica'],
            ['prefix' => '507', 'country_code' => 'PA', 'country_name' => 'Panama'],
            ['prefix' => '508', 'country_code' => 'PM', 'country_name' => 'Saint Pierre'],
            ['prefix' => '509', 'country_code' => 'HT', 'country_name' => 'Haiti'],
            ['prefix' => '590', 'country_code' => 'GP', 'country_name' => 'Guadeloupe'],
            ['prefix' => '591', 'country_code' => 'BO', 'country_name' => 'Bolivia'],
            ['prefix' => '592', 'country_code' => 'GY', 'country_name' => 'Guyana'],
            ['prefix' => '593', 'country_code' => 'EC', 'country_name' => 'Ecuador'],
            ['prefix' => '594', 'country_code' => 'GF', 'country_name' => 'French Guiana'],
            ['prefix' => '595', 'country_code' => 'PY', 'country_name' => 'Paraguay'],
            ['prefix' => '596', 'country_code' => 'MQ', 'country_name' => 'Martinique'],
            ['prefix' => '597', 'country_code' => 'SR', 'country_name' => 'Suriname'],
            ['prefix' => '598', 'country_code' => 'UY', 'country_name' => 'Uruguay'],
            ['prefix' => '599', 'country_code' => 'CW', 'country_name' => 'Curacao'],
            ['prefix' => '670', 'country_code' => 'TL', 'country_name' => 'Timor-Leste'],
            ['prefix' => '672', 'country_code' => 'NF', 'country_name' => 'Norfolk Island'],
            ['prefix' => '673', 'country_code' => 'BN', 'country_name' => 'Brunei'],
            ['prefix' => '674', 'country_code' => 'NR', 'country_name' => 'Nauru'],
            ['prefix' => '675', 'country_code' => 'PG', 'country_name' => 'Papua New Guinea'],
            ['prefix' => '676', 'country_code' => 'TO', 'country_name' => 'Tonga'],
            ['prefix' => '677', 'country_code' => 'SB', 'country_name' => 'Solomon Islands'],
            ['prefix' => '678', 'country_code' => 'VU', 'country_name' => 'Vanuatu'],
            ['prefix' => '679', 'country_code' => 'FJ', 'country_name' => 'Fiji'],
            ['prefix' => '680', 'country_code' => 'PW', 'country_name' => 'Palau'],
            ['prefix' => '681', 'country_code' => 'WF', 'country_name' => 'Wallis and Futuna'],
            ['prefix' => '682', 'country_code' => 'CK', 'country_name' => 'Cook Islands'],
            ['prefix' => '683', 'country_code' => 'NU', 'country_name' => 'Niue'],
            ['prefix' => '684', 'country_code' => 'AS', 'country_name' => 'American Samoa'],
            ['prefix' => '685', 'country_code' => 'WS', 'country_name' => 'Samoa'],
            ['prefix' => '686', 'country_code' => 'KI', 'country_name' => 'Kiribati'],
            ['prefix' => '687', 'country_code' => 'NC', 'country_name' => 'New Caledonia'],
            ['prefix' => '688', 'country_code' => 'TV', 'country_name' => 'Tuvalu'],
            ['prefix' => '689', 'country_code' => 'PF', 'country_name' => 'French Polynesia'],
            ['prefix' => '690', 'country_code' => 'TK', 'country_name' => 'Tokelau'],
            ['prefix' => '691', 'country_code' => 'FM', 'country_name' => 'Micronesia'],
            ['prefix' => '692', 'country_code' => 'MH', 'country_name' => 'Marshall Islands'],
            ['prefix' => '850', 'country_code' => 'KP', 'country_name' => 'North Korea'],
            ['prefix' => '852', 'country_code' => 'HK', 'country_name' => 'Hong Kong'],
            ['prefix' => '853', 'country_code' => 'MO', 'country_name' => 'Macau'],
            ['prefix' => '855', 'country_code' => 'KH', 'country_name' => 'Cambodia'],
            ['prefix' => '856', 'country_code' => 'LA', 'country_name' => 'Laos'],
            ['prefix' => '880', 'country_code' => 'BD', 'country_name' => 'Bangladesh'],
            ['prefix' => '886', 'country_code' => 'TW', 'country_name' => 'Taiwan'],
            ['prefix' => '960', 'country_code' => 'MV', 'country_name' => 'Maldives'],
            ['prefix' => '961', 'country_code' => 'LB', 'country_name' => 'Lebanon'],
            ['prefix' => '962', 'country_code' => 'JO', 'country_name' => 'Jordan'],
            ['prefix' => '963', 'country_code' => 'SY', 'country_name' => 'Syria'],
            ['prefix' => '964', 'country_code' => 'IQ', 'country_name' => 'Iraq'],
            ['prefix' => '965', 'country_code' => 'KW', 'country_name' => 'Kuwait'],
            ['prefix' => '966', 'country_code' => 'SA', 'country_name' => 'Saudi Arabia'],
            ['prefix' => '967', 'country_code' => 'YE', 'country_name' => 'Yemen'],
            ['prefix' => '968', 'country_code' => 'OM', 'country_name' => 'Oman'],
            ['prefix' => '970', 'country_code' => 'PS', 'country_name' => 'Palestine'],
            ['prefix' => '971', 'country_code' => 'AE', 'country_name' => 'United Arab Emirates'],
            ['prefix' => '972', 'country_code' => 'IL', 'country_name' => 'Israel'],
            ['prefix' => '973', 'country_code' => 'BH', 'country_name' => 'Bahrain'],
            ['prefix' => '974', 'country_code' => 'QA', 'country_name' => 'Qatar'],
            ['prefix' => '975', 'country_code' => 'BT', 'country_name' => 'Bhutan'],
            ['prefix' => '976', 'country_code' => 'MN', 'country_name' => 'Mongolia'],
            ['prefix' => '977', 'country_code' => 'NP', 'country_name' => 'Nepal'],
            ['prefix' => '992', 'country_code' => 'TJ', 'country_name' => 'Tajikistan'],
            ['prefix' => '993', 'country_code' => 'TM', 'country_name' => 'Turkmenistan'],
            ['prefix' => '994', 'country_code' => 'AZ', 'country_name' => 'Azerbaijan'],
            ['prefix' => '995', 'country_code' => 'GE', 'country_name' => 'Georgia'],
            ['prefix' => '996', 'country_code' => 'KG', 'country_name' => 'Kyrgyzstan'],
            ['prefix' => '998', 'country_code' => 'UZ', 'country_name' => 'Uzbekistan'],
        ];

        \DB::table('country_prefixes')->insert($prefixes);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('country_prefixes');
    }
};
